// Human creative control is independent of the model's automatic bookkeeping.
// These are calling-LLM instructions, not a server-side approval mechanism.
export const storyScopeInstructions = `Respect the human author's starting brief and chosen involvement. For a new story, ask about unresolved initial settings and writing-process involvement separately; reuse explicit preferences and delegation. Offer setting all or some parameters or delegating them, and autonomous work, selected checkpoints, ongoing collaboration, or a custom arrangement. Read life-sim://addon/storytelling for intake guidance. Automatic modeling and reviews operate within that agreement. Wait for the human at agreed approval checkpoints; saving a proposal or passing a review is not their approval. A bounded review or edit request does not require a new-project questionnaire.`;

export const storyIntakeInstructions = `Before developing a new story, establish what the human author wants to control. The human author is the user; the calling LLM may do the writing and modeling, but its authorId or review findings do not stand in for human decisions. Reuse preferences already given in the conversation or established authoring record. Ask only what remains unresolved, usually in two short questions:
1. Starting settings: Would you like to set the story's initial parameters, choose just some and leave the rest to me, or have me propose them? Offer examples such as genre, length, number of principal characters, audience, tone, authorial voice or persona, reasons for writing this work, setting, viewpoint, premise, and fixed constraints or ending. These are examples, not a required form; do not ask for every parameter or require an exhaustive brief. Retain supplied choices and distinguish fixed requirements, open choices, and proposed defaults. Delegating initial settings does not also delegate the rest of the writing process.
2. Ongoing involvement: Should I complete the agreed work autonomously, return at selected milestones, collaborate with you throughout, or follow another arrangement? Possible checkpoints include the author model, premise, principal characters and life trajectories, plot or ending, an outline, each chapter, and major revisions. Ask which checkpoints matter only if needed. Clarify whether a checkpoint is an approval decision or a progress update; do not treat a request for updates as a requirement to stop. An author may supply a detailed brief and then delegate everything, or delegate the premise and remain involved in writing. Review-only or idea-development help is also a valid limited role.
For autonomous work, choose and revise within the delegated brief and deliver the agreed result without routine interruptions. With approval checkpoints, present a concrete, concise proposal and useful alternatives, then wait before adopting it or doing work that depends on approval. In ongoing collaboration, agree the next useful piece of work rather than seeking permission for every tool call. An unanswered question is not consent; do not silently choose autonomous mode. Explicit instructions such as choosing the premise and delivering a finished story already establish delegation for that task, so do not repeat the intake. A bounded request to review, edit, name, or explore existing material is not permission to launch an entire story project and does not require this full intake.
The author can change either choice at any time. Their current instructions take precedence over older records. Keep automatic life modeling, numerical exploration, model-depth checks, and editorial reviews within the agreed role; do not transfer routine modeling work to the human. Propose a necessary creative repair for approval when it crosses a reserved decision, rather than silently changing the brief or weakening a consistency check.
Once the model and story graph exist, store the brief, the human's actual instructions, and both choices through life_story_author_record with explicit author-only scopes: context for the brief and selection for the collaboration agreement. Its data can distinguish supplied parameters, delegated choices, proposed defaults, checkpoints, and approval versus update expectations. Identify whether a decision came from the human or the LLM acting under delegation. Save later changes as new records linked with supersedes; never invent a human approval. These records guide the calling LLM and preserve provenance; the server does not independently verify human consent.`;
